import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { stripLatexDelimiters } from '@/lib/latex-utils';

const TYPE_LABELS: Record<string, string> = {
  mcq: 'MCQ',
  fill: 'Fill in the Blank',
  short: 'Short Answer',
  long: 'Long Answer',
  true_false: 'True / False',
  match: 'Match the Following',
};

const COLORS = {
  primary: [79, 70, 229] as [number, number, number],     // indigo-600
  success: [16, 185, 129] as [number, number, number],     // emerald-500
  danger: [239, 68, 68] as [number, number, number],       // red-500
  muted: [107, 114, 128] as [number, number, number],      // gray-500
  dark: [17, 24, 39] as [number, number, number],           // gray-900
  light: [249, 250, 251] as [number, number, number],       // gray-50
  white: [255, 255, 255] as [number, number, number],
};

function addHeader(doc: jsPDF, title: string, subtitle?: string) {
  const pageW = doc.internal.pageSize.getWidth();
  // Brand bar
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageW, 28, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...COLORS.white);
  doc.text('GenVerse', 14, 12);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Assessment Platform', 14, 19);

  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.dark);
  doc.text(title, 14, 42);

  if (subtitle) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.muted);
    doc.text(subtitle, 14, 50);
  }
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageH = doc.internal.pageSize.getHeight();
    const pageW = doc.internal.pageSize.getWidth();
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.text(`Page ${i} of ${pageCount}`, pageW / 2, pageH - 8, { align: 'center' });
    doc.text('Generated by GenVerse', 14, pageH - 8);
  }
}

function optionLabel(idx: number): string {
  return String.fromCharCode(65 + idx); // A, B, C, D...
}

/** Download assessment questions as PDF (with or without answers) */
export function downloadAssessmentPDF(
  assessment: {
    title: string;
    subject?: string;
    difficulty?: string;
    question_json: any[];
    answer_key_json?: any[];
  },
  withAnswers: boolean,
) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 14;
  const contentW = pageW - margin * 2;

  addHeader(doc, assessment.title || 'Assessment', withAnswers ? 'Answer Key Included' : 'Question Paper');

  // Metadata row
  let y = 56;
  const metaParts: string[] = [];
  if (assessment.subject) metaParts.push(`Subject: ${assessment.subject}`);
  if (assessment.difficulty) metaParts.push(`Difficulty: ${assessment.difficulty}`);
  metaParts.push(`Questions: ${assessment.question_json.length}`);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.muted);
  doc.text(metaParts.join('   |   '), margin, y);
  y += 4;

  // Divider
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  const questions = assessment.question_json || [];
  const answerKey = assessment.answer_key_json || [];

  questions.forEach((q: any, idx: number) => {
    const qType = TYPE_LABELS[q.type] || q.type || 'Question';
    const points = q.points || 1;
    const keyEntry = answerKey.find((k: any) => k.id === q.id);

    // Check if we need a new page (estimate space needed)
    const estimatedHeight = 30 + (q.options?.length || 0) * 7 + (withAnswers ? 20 : 0);
    if (y + estimatedHeight > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = 16;
    }

    // Question number + type badge + points
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.dark);
    doc.text(`Q${idx + 1}.`, margin, y);

    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    // Type badge
    const badgeX = margin + 12;
    const badgeText = qType;
    const badgeWidth = doc.getTextWidth(badgeText) + 4;
    doc.setFillColor(238, 242, 255);
    doc.roundedRect(badgeX, y - 3.5, badgeWidth, 5, 1, 1, 'F');
    doc.setTextColor(...COLORS.primary);
    doc.text(badgeText, badgeX + 2, y);

    // Points
    const ptsText = `${points} pt${points !== 1 ? 's' : ''}`;
    doc.setTextColor(...COLORS.muted);
    doc.text(ptsText, pageW - margin, y, { align: 'right' });

    y += 5;

    // Question text - handle long text wrapping
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.dark);
    const textLines = doc.splitTextToSize(stripLatexDelimiters(q.text || ''), contentW - 5);
    doc.text(textLines, margin + 4, y);
    y += textLines.length * 4.5 + 2;

    // Options for MCQ
    if ((q.type === 'mcq' || q.type === 'true_false') && Array.isArray(q.options) && q.options.length > 0) {
      const correctAnswer = withAnswers ? (q.correctAnswer ?? keyEntry?.correctAnswer) : null;

      q.options.forEach((opt: string, oi: number) => {
        if (y + 6 > doc.internal.pageSize.getHeight() - 20) {
          doc.addPage();
          y = 16;
        }

        const label = optionLabel(oi);
        const isCorrect = correctAnswer != null && (
          correctAnswer === oi ||
          correctAnswer === label ||
          String(correctAnswer).toLowerCase() === String(opt).toLowerCase() ||
          String(correctAnswer) === String(oi)
        );

        if (isCorrect) {
          // Highlight correct answer
          doc.setFillColor(236, 253, 245);
          doc.roundedRect(margin + 4, y - 3.5, contentW - 8, 5.5, 1, 1, 'F');
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(...COLORS.success);
        } else {
          doc.setFont('helvetica', 'normal');
          doc.setTextColor(...COLORS.dark);
        }

        doc.setFontSize(9);
        const optText = `${label}.  ${stripLatexDelimiters(opt)}`;
        doc.text(optText, margin + 8, y);

        if (isCorrect) {
          doc.text('  ✓', margin + 8 + doc.getTextWidth(optText), y);
        }

        y += 6;
      });
    }

    // True/False without explicit options
    if (q.type === 'true_false' && (!q.options || q.options.length === 0)) {
      const correctAnswer = withAnswers ? (q.correctAnswer ?? keyEntry?.correctAnswer) : null;
      ['True', 'False'].forEach((opt, oi) => {
        const isCorrect = correctAnswer != null && String(correctAnswer).toLowerCase() === opt.toLowerCase();
        if (isCorrect) {
          doc.setFillColor(236, 253, 245);
          doc.roundedRect(margin + 4, y - 3.5, contentW - 8, 5.5, 1, 1, 'F');
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(...COLORS.success);
        } else {
          doc.setFont('helvetica', 'normal');
          doc.setTextColor(...COLORS.dark);
        }
        doc.setFontSize(9);
        doc.text(`${optionLabel(oi)}.  ${opt}`, margin + 8, y);
        if (isCorrect) doc.text('  ✓', margin + 8 + doc.getTextWidth(`${optionLabel(oi)}.  ${opt}`), y);
        y += 6;
      });
    }

    // Short/long answer - show blank line or answer
    if (q.type === 'short' || q.type === 'long' || q.type === 'fill') {
      if (withAnswers) {
        const answer = q.correctAnswer ?? keyEntry?.correctAnswer ?? '';
        if (answer) {
          doc.setFontSize(9);
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(...COLORS.success);
          doc.text('Answer: ', margin + 4, y);
          doc.setFont('helvetica', 'normal');
          const ansLines = doc.splitTextToSize(stripLatexDelimiters(String(answer)), contentW - 20);
          doc.text(ansLines, margin + 4 + doc.getTextWidth('Answer: '), y);
          y += ansLines.length * 4.5;
        }
      } else {
        // Blank lines for writing
        doc.setDrawColor(200, 200, 200);
        doc.setLineWidth(0.2);
        const lineCount = q.type === 'long' ? 4 : 2;
        for (let l = 0; l < lineCount; l++) {
          doc.line(margin + 4, y + 2, pageW - margin, y + 2);
          y += 6;
        }
      }
    }

    // Matching pairs
    if (q.type === 'match' && Array.isArray(q.pairs)) {
      const tableBody = q.pairs.map((p: any, pi: number) => [
        String(pi + 1),
        stripLatexDelimiters(p.term || p.left || ''),
        withAnswers ? stripLatexDelimiters(p.definition || p.right || '') : '',
      ]);

      autoTable(doc, {
        startY: y,
        head: [['#', 'Term', withAnswers ? 'Definition' : 'Match']],
        body: tableBody,
        margin: { left: margin + 4 },
        tableWidth: contentW - 8,
        styles: { fontSize: 8, cellPadding: 2 },
        headStyles: { fillColor: COLORS.primary, textColor: COLORS.white },
        theme: 'grid',
      });
      y = (doc as any).lastAutoTable?.finalY + 4 || y + 30;
    }

    // Explanation (with answers only)
    if (withAnswers && (q.explanation || keyEntry?.explanation)) {
      const explanation = q.explanation || keyEntry?.explanation;
      if (y + 10 > doc.internal.pageSize.getHeight() - 20) {
        doc.addPage();
        y = 16;
      }
      doc.setFontSize(8);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(...COLORS.muted);
      const expLines = doc.splitTextToSize(`Explanation: ${stripLatexDelimiters(explanation)}`, contentW - 10);
      doc.text(expLines, margin + 4, y);
      y += expLines.length * 3.5 + 2;
    }

    // Space between questions
    y += 4;
  });

  addFooter(doc);

  const filename = `${assessment.title || 'assessment'}${withAnswers ? '-with-answers' : ''}.pdf`;
  doc.save(filename);
}

/** Download score report as PDF */
export function downloadScoreReportPDF(
  historyItem: {
    score: number;
    max_score: number;
    percentage: number;
    time_taken_seconds?: number;
    created_at?: string;
    subject?: string;
    difficulty?: string;
    topics?: string[];
  },
  detail?: {
    attempt: { responses_json: any };
    assessment: { title: string; question_json: any[]; answer_key_json?: any[] };
  } | null,
) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 14;
  const contentW = pageW - margin * 2;

  const title = detail?.assessment?.title || 'Score Report';
  addHeader(doc, title, 'Performance Report');

  let y = 56;

  // ── Score summary cards (as a table) ──
  const pct = historyItem.percentage;
  const scoreColor: [number, number, number] = pct >= 70 ? COLORS.success : pct >= 40 ? [245, 158, 11] : COLORS.danger;

  // Score ring (circle)
  const ringX = margin + 20;
  const ringY = y + 14;
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(2);
  doc.circle(ringX, ringY, 12, 'S');
  // Colored arc overlay
  doc.setDrawColor(...scoreColor);
  doc.setLineWidth(2.5);
  // Draw arc (approximate with a filled circle overlay)
  doc.circle(ringX, ringY, 12, 'S');
  // Score text
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...scoreColor);
  doc.text(`${pct}%`, ringX, ringY + 1.5, { align: 'center' });

  // Summary details next to score ring
  const detailX = margin + 42;
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.dark);
  doc.text(`${historyItem.score} / ${historyItem.max_score}`, detailX, y + 6);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.muted);
  const summaryParts: string[] = [];
  if (historyItem.subject) summaryParts.push(`Subject: ${historyItem.subject}`);
  if (historyItem.difficulty) summaryParts.push(`Difficulty: ${historyItem.difficulty}`);
  if (historyItem.time_taken_seconds) {
    const mins = Math.floor(historyItem.time_taken_seconds / 60);
    const secs = historyItem.time_taken_seconds % 60;
    summaryParts.push(`Time: ${mins}m ${secs}s`);
  }
  if (historyItem.created_at) {
    const d = new Date(historyItem.created_at);
    summaryParts.push(`Date: ${d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })}`);
  }
  doc.text(summaryParts.join('   |   '), detailX, y + 14);

  if (historyItem.topics && historyItem.topics.length > 0) {
    doc.text(`Topics: ${historyItem.topics.join(', ')}`, detailX, y + 20);
  }

  y += 36;

  // Divider
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  // ── Question-by-question breakdown ──
  if (detail?.attempt?.responses_json && detail?.assessment?.question_json) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.dark);
    doc.text('Question Breakdown', margin, y);
    y += 6;

    const questions = detail.assessment.question_json as any[];
    const answerKey = detail.assessment.answer_key_json || [];
    const rawResponses = detail.attempt.responses_json;
    const responsesDict: Record<string, string> = Array.isArray(rawResponses)
      ? Object.fromEntries((rawResponses as any[]).map((r: any) => [r.questionId, r.answer]))
      : (rawResponses as Record<string, string> || {});

    // Summary table
    const tableBody = questions.map((q: any, idx: number) => {
      const userAnswer = responsesDict[q.id] ?? '-';
      const keyEntry = answerKey.find((k: any) => k.id === q.id);
      const correctAnswer = q.correctAnswer != null ? String(q.correctAnswer)
        : keyEntry?.correctAnswer != null ? String(keyEntry.correctAnswer) : '-';

      // Resolve display answer for MCQs
      let userDisplay = userAnswer;
      let correctDisplay = correctAnswer;
      if (q.type === 'mcq' && Array.isArray(q.options)) {
        const uIdx = parseInt(userAnswer);
        if (!isNaN(uIdx) && q.options[uIdx]) userDisplay = `${optionLabel(uIdx)}. ${q.options[uIdx]}`;
        const cIdx = parseInt(correctAnswer);
        if (!isNaN(cIdx) && q.options[cIdx]) correctDisplay = `${optionLabel(cIdx)}. ${q.options[cIdx]}`;
      }

      const isCorrect = userAnswer !== '-'
        ? userAnswer.trim().toLowerCase() === correctAnswer.trim().toLowerCase()
        : null;

      return [
        String(idx + 1),
        stripLatexDelimiters((q.text || '').substring(0, 80) + ((q.text?.length || 0) > 80 ? '…' : '')),
        userDisplay,
        correctDisplay,
        isCorrect === true ? '✓' : isCorrect === false ? '✗' : '-',
      ];
    });

    autoTable(doc, {
      startY: y,
      head: [['#', 'Question', 'Your Answer', 'Correct Answer', '']],
      body: tableBody,
      margin: { left: margin },
      tableWidth: contentW,
      styles: { fontSize: 8, cellPadding: 2, overflow: 'linebreak' },
      headStyles: { fillColor: COLORS.primary, textColor: COLORS.white, fontStyle: 'bold' },
      columnStyles: {
        0: { cellWidth: 8, halign: 'center' },
        1: { cellWidth: 60 },
        4: { cellWidth: 8, halign: 'center', fontStyle: 'bold' },
      },
      didParseCell(data) {
        if (data.section === 'body' && data.column.index === 4) {
          const val = data.cell.text[0];
          if (val === '✓') data.cell.styles.textColor = COLORS.success;
          else if (val === '✗') data.cell.styles.textColor = COLORS.danger;
        }
      },
      theme: 'grid',
    });

    y = (doc as any).lastAutoTable?.finalY + 10 || y + 30;

    // ── Detailed question-by-question review ──
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.dark);
    if (y + 10 > doc.internal.pageSize.getHeight() - 20) { doc.addPage(); y = 16; }
    doc.text('Detailed Review', margin, y);
    y += 8;

    questions.forEach((q: any, idx: number) => {
      const qKeyEntry = answerKey.find((k: any) => k.id === q.id);
      const userAnswer = responsesDict[q.id] ?? '-';
      const correctAns = q.correctAnswer != null ? String(q.correctAnswer)
        : qKeyEntry?.correctAnswer != null ? String(qKeyEntry.correctAnswer) : '-';

      const isCorrect = userAnswer !== '-'
        ? userAnswer.trim().toLowerCase() === correctAns.trim().toLowerCase()
        : null;

      // Estimate space needed
      const estHeight = 35 + (q.options?.length || 0) * 6 + (qKeyEntry?.explanation ? 12 : 0);
      if (y + estHeight > doc.internal.pageSize.getHeight() - 20) { doc.addPage(); y = 16; }

      // Question header
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.dark);
      const statusIcon = isCorrect === true ? '  ✓' : isCorrect === false ? '  ✗' : '';
      doc.text(`Q${idx + 1}.`, margin, y);

      // Type badge
      const qType = TYPE_LABELS[q.type] || q.type || 'Question';
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      const bX = margin + 12;
      const bW = doc.getTextWidth(qType) + 4;
      doc.setFillColor(238, 242, 255);
      doc.roundedRect(bX, y - 3.5, bW, 5, 1, 1, 'F');
      doc.setTextColor(...COLORS.primary);
      doc.text(qType, bX + 2, y);

      // Status
      if (isCorrect === true) {
        doc.setTextColor(...COLORS.success);
        doc.setFont('helvetica', 'bold');
        doc.text('Correct', pageW - margin, y, { align: 'right' });
      } else if (isCorrect === false) {
        doc.setTextColor(...COLORS.danger);
        doc.setFont('helvetica', 'bold');
        doc.text('Incorrect', pageW - margin, y, { align: 'right' });
      }
      y += 5;

      // Question text
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLORS.dark);
      const qLines = doc.splitTextToSize(stripLatexDelimiters(q.text || ''), contentW - 5);
      doc.text(qLines, margin + 4, y);
      y += qLines.length * 4 + 3;

      // Options with highlighting
      if ((q.type === 'mcq' || q.type === 'true_false') && Array.isArray(q.options) && q.options.length > 0) {
        q.options.forEach((opt: string, oi: number) => {
          if (y + 6 > doc.internal.pageSize.getHeight() - 20) { doc.addPage(); y = 16; }
          const label = optionLabel(oi);
          const isUserAnswer = String(userAnswer) === String(oi) || String(userAnswer) === label;
          const isCorrectOpt = String(correctAns) === String(oi) || String(correctAns) === label
            || String(correctAns).toLowerCase() === String(opt).toLowerCase();

          if (isCorrectOpt) {
            doc.setFillColor(236, 253, 245);
            doc.roundedRect(margin + 4, y - 3.5, contentW - 8, 5.5, 1, 1, 'F');
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(...COLORS.success);
          } else if (isUserAnswer && !isCorrect) {
            doc.setFillColor(254, 242, 242);
            doc.roundedRect(margin + 4, y - 3.5, contentW - 8, 5.5, 1, 1, 'F');
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(...COLORS.danger);
          } else {
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(...COLORS.dark);
          }

          doc.setFontSize(8);
          const optText = `${label}. ${stripLatexDelimiters(opt)}`;
          doc.text(optText, margin + 8, y);

          if (isCorrectOpt) doc.text('  ✓', margin + 8 + doc.getTextWidth(optText), y);
          if (isUserAnswer && !isCorrect) {
            const yourText = '  (your answer)';
            doc.setFontSize(7);
            doc.text(yourText, margin + 8 + doc.getTextWidth(optText), y);
          }
          y += 6;
        });
      }

      // Short/fill/long answer display
      if (q.type === 'short' || q.type === 'long' || q.type === 'fill') {
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...COLORS.muted);
        doc.text('Your answer:', margin + 4, y);
        doc.setTextColor(...(isCorrect ? COLORS.success : COLORS.danger));
        doc.setFont('helvetica', 'bold');
        const uaLines = doc.splitTextToSize(String(userAnswer), contentW - 30);
        doc.text(uaLines, margin + 28, y);
        y += uaLines.length * 4 + 2;

        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...COLORS.muted);
        doc.text('Correct answer:', margin + 4, y);
        doc.setTextColor(...COLORS.success);
        doc.setFont('helvetica', 'bold');
        const caLines = doc.splitTextToSize(String(correctAns), contentW - 30);
        doc.text(caLines, margin + 30, y);
        y += caLines.length * 4 + 2;
      }

      // Explanation
      const explanation = q.explanation || qKeyEntry?.explanation;
      if (explanation) {
        if (y + 8 > doc.internal.pageSize.getHeight() - 20) { doc.addPage(); y = 16; }
        doc.setFontSize(8);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(...COLORS.muted);
        const expLines = doc.splitTextToSize(`Explanation: ${stripLatexDelimiters(explanation)}`, contentW - 10);
        doc.text(expLines, margin + 4, y);
        y += expLines.length * 3.5 + 2;
      }

      // Separator
      y += 2;
      doc.setDrawColor(229, 231, 235);
      doc.setLineWidth(0.2);
      doc.line(margin, y, pageW - margin, y);
      y += 5;
    });
  }

  addFooter(doc);

  const filename = `score-report-${historyItem.percentage}pct.pdf`;
  doc.save(filename);
}
